### ISSUE TITLE
VS crashes during Build of nupkg file

### ISSUE THREAD

**Issue by graymatter00** [MrPickles2009/NupkgManager#1]
Using Visual Studio 2019 Community.  Created a nuspec file (verified using XSD), open Nupkg Manager, select project's nuspec file, click the Build button.

Visual Studio crashes within a few seconds, then Visual Studio re-starts.  Banner error message in VS states that Mupkg Manager caused the crash.

What other information can I send you?

**Comment by MrPickles2009** [comment]
I haven't experienced this but will try and do some debugging

**Comment by Illinariss** [comment]
I have the same problem as @graymatter00.

Here is some text from the application log of the Windows Event Viewer. 
I hope it can help. (just ignore the german words between...  bei = at )

`System.FormatException
   bei System.Number.StringToNumber(System.String, System.Globalization.NumberStyles, NumberBuffer ByRef, System.Globalization.NumberFormatInfo, Boolean)
   bei System.Number.ParseInt32(System.String, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo)
   bei NupkgManager.MainPage.IncrementVersionNumber(System.String)
   bei NupkgManager.MainPage.BuildPackages()
   bei NupkgManager.MainPage.buildPackagesButton_Click(System.Object, System.EventArgs)
   bei System.Windows.Forms.Control.OnClick(System.EventArgs)
   bei System.Windows.Forms.Button.OnClick(System.EventArgs)
   bei System.Windows.Forms.Button.OnMouseUp(System.Windows.Forms.MouseEventArgs)
   bei System.Windows.Forms.Control.WmMouseUp(System.Windows.Forms.Message ByRef, System.Windows.Forms.MouseButtons, Int32)
   bei System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   bei System.Windows.Forms.ButtonBase.WndProc(System.Windows.Forms.Message ByRef)
   bei System.Windows.Forms.Button.WndProc(System.Windows.Forms.Message ByRef)
   bei System.Windows.Forms.Control+ControlNativeWindow.OnMessage(System.Windows.Forms.Message ByRef)
   bei System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message ByRef)
   bei System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr, Int32, IntPtr, IntPtr)`

**Comment by MrPickles2009** [comment]
It should be working for you both now. Thanks @Illinariss for the logs

If you have any other errors relating to building feel free to reopen this issue
